# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='用户名')),
                ('upassword', models.CharField(max_length=50, verbose_name='密码')),
                ('uemail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('ureceive', models.CharField(max_length=50, verbose_name='收件人')),
                ('uaddress', models.CharField(max_length=100, verbose_name='地址')),
                ('uzip_code', models.CharField(max_length=30, verbose_name='邮编')),
                ('uphone', models.IntegerField(max_length=11, verbose_name='手机号')),
            ],
        ),
    ]
