# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenong_users', '0002_auto_20180614_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uaddress',
            field=models.CharField(default='', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(default='', max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ureceive',
            field=models.CharField(default='', max_length=50, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uzip_code',
            field=models.CharField(default='', max_length=30, verbose_name='邮编'),
        ),
    ]
